name: t-iot-902-back-end

services:
  # Backend Rust
  rust-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./backend:/app
      - /app/target # Exclure le dossier target pour éviter les conflits
    environment:
      - RUST_LOG=${RUST_LOG}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - SENSOR_COMMUNITY_ID=${SENSOR_COMMUNITY_ID}
      - SENSOR_COMMUNITY_PIN=${SENSOR_COMMUNITY_PIN}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - TEST_SENSOR_COMMUNITY=${TEST_SENSOR_COMMUNITY}
      - SENSOR_LOCATION=${SENSOR_LOCATION}
      - DHT_SENSOR_ID=${DHT_SENSOR_ID}
      - SOUND_SENSOR_ID=${SOUND_SENSOR_ID}
      - DUST_SENSOR_ID=${DUST_SENSOR_ID}
      - SENSOR_COMMUNITY_URL=${SENSOR_COMMUNITY_URL}
    depends_on:
      - influxdb

  # InfluxDB pour le stockage des données temporelles
  influxdb:
    image: influxdb:2.7
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_RETENTION}

  # Grafana pour la visualisation
  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    entrypoint: >
      sh -c "
        chmod +x /etc/grafana/provisioning/init-config.sh &&
        /etc/grafana/provisioning/init-config.sh &&
        /run.sh
      "
    depends_on:
      - influxdb

volumes:
  influxdb-data:
  grafana-data:
